echo grafana_grafana tar is creating on external drive...
docker export 07a0072da54f |gzip > /media/pi/DriveCos/grafana_grafana.tar.gz
echo influxdb_1.8 tar is creating on external drive...
docker export fb34410bbad7 |gzip > /media/pi/DriveCos/influxdb_1.8.tar.gz
echo iotstack_zigbee2mqtt_latest tar is creating on external drive...
docker export 96101b2af602 |gzip > /media/pi/DriveCos/iotstack_zigbee2mqtt_latest.tar.gz
echo iotstack_nodered tar is creating on external drive...
docker export 93092f5f54af |gzip > /media/pi/DriveCos/iotstack_nodered.tar.gz
echo portainer_portainer-ce tar is creating on external drive...
docker export 556031e55785 |gzip > /media/pi/DriveCos/portainer_portainer-ce.tar.gz
echo iotstack_mosquitto tar is creating on external drive...
docker export 36ec1f1c7376 |gzip > /media/pi/DriveCos/iotstack_mosquitto.tar.gz
