echo iotstack_mosquitto tar is creating on local drive...
docker export c8688245a4d5 |gzip > /home/pi/containers/iotstack_mosquitto.tar.gz
echo pihole__pihole_latest tar is creating on local drive...
docker export abe4a0df7c04 |gzip > /home/pi/containers/pihole__pihole_latest.tar.gz
echo influxdb_1.8 tar is creating on local drive...
docker export 3e620030bbb4 |gzip > /home/pi/containers/influxdb_1.8.tar.gz
echo iotstack_nodered tar is creating on local drive...
docker export 9d868e12f499 |gzip > /home/pi/containers/iotstack_nodered.tar.gz
echo grafana__grafana tar is creating on local drive...
docker export 62c7a12da801 |gzip > /home/pi/containers/grafana__grafana.tar.gz
echo portainer__portainer-ce tar is creating on local drive...
docker export a61c6861cebf |gzip > /home/pi/containers/portainer__portainer-ce.tar.gz
echo ">>>>>>>>>>>>>> ARCHAVING IOTStack folder................\n"
sudo tar -czvf IOTstack.tar.gz /home/pi/IOTstack/
echo "Copy containers files in ..."
sudo cp -r  /home/pi/containers/* /media/pi/DriveCos/IOT_boot_camp/save/ 
sudo cp -r  /home/pi/work/backup/docker_backup/IOTstack.tar.gz /media/pi/DriveCos/IOT_boot_camp/save/ 
